POST http://localhost:7500/api/user/auth HTTP/1.1
Content-type: application/json

{
    "email" : "jamal@gmail.com",
    "password": "jamal"
}


###
POST http://localhost:7500/api/user/register HTTP/1.1
Content-type: application/json

{
    "firstName": "Jamal",
    "lastName": "Pelpuo",
    "email": "jamal@jamal.com",
    "password": "jamal"
}